[build]
  command = ""   # plain HTML site
  publish = "/"

[functions]
  directory = "netlify/functions"

# keep your SPA redirect so /about etc work
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
